import type { ReactNode } from 'react'
import { Box, Text } from 'ink'

import { LOGO, type LogoCell } from '../logo-art'

interface Run {
  text: string
  fg?: string
  bg?: string
}

/** Collapses consecutive cells that share the same colours into one run, so one `<Text>` draws a whole bar instead of one per pixel. */
function mergeRuns(row: LogoCell[]): Run[] {
  const runs: Run[] = []
  for (const cell of row) {
    const last = runs[runs.length - 1]
    if (last !== undefined && last.fg === cell.fg && last.bg === cell.bg) {
      last.text += cell.char
    } else {
      runs.push({ text: cell.char, fg: cell.fg, bg: cell.bg })
    }
  }
  return runs
}

const MIN_COLUMNS_FOR_ART = 40
const MIN_COLUMNS_FOR_ROW_LAYOUT = 70

/**
 * Albus's face, drawn with Unicode half blocks + truecolor (see
 * `../logo-art.ts`, generated by `npm run logo:render` from `docs/logo.png`).
 * Terminal image protocols (Sixel/Kitty) are not reliable across Windows
 * Terminal, Orca and plain conhost, so this is the portable path.
 *
 * Degrades to the bold wordmark alone below 40 columns, or when `NO_COLOR`
 * is set — half-block art needs truecolor, and there is nowhere for a
 * 30-column drawing to shrink to below that width anyway.
 */
export function Logo(): ReactNode {
  const columns = process.stdout.columns ?? 80
  const plain = columns < MIN_COLUMNS_FOR_ART || process.env.NO_COLOR !== undefined

  if (plain) {
    return <Text bold>ALBUS</Text>
  }

  const stacked = columns < MIN_COLUMNS_FOR_ROW_LAYOUT

  return (
    <Box flexDirection={stacked ? 'column' : 'row'} alignItems={stacked ? 'flex-start' : 'center'}>
      <Box flexDirection="column">
        {LOGO.map((row, rowIndex) => (
          <Text key={rowIndex}>
            {mergeRuns(row).map((run, runIndex) => (
              <Text key={runIndex} color={run.fg} backgroundColor={run.bg}>
                {run.text}
              </Text>
            ))}
          </Text>
        ))}
      </Box>
      <Box flexDirection="column" marginLeft={stacked ? 0 : 2} marginTop={stacked ? 1 : 0}>
        <Text bold>ALBUS</Text>
        <Text dimColor>setup</Text>
      </Box>
    </Box>
  )
}
