/**
 * Renders `docs/logo.png` (Albus's face: white wizard-in-a-triangle on a
 * transparent background, one orange diamond in the beard) into
 * `src/tui/logo-art.ts` as a grid of Unicode half-block cells with truecolor
 * foreground/background — the same trick most TUI banners use, since Sixel
 * and Kitty graphics protocols are not reliable across Windows Terminal,
 * Orca and plain conhost.
 *
 *   npm run logo:render
 *
 * Each text row covers two pixel rows: the top pixel becomes the `▀`
 * foreground, the bottom pixel its background (half-block trick). Colours
 * are quantized to the two-tone palette the mark actually uses — there is
 * no in-between in the source art, so nearest-by-hue classification is
 * exact, not an approximation.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'

const SOURCE = path.join(__dirname, '..', 'docs', 'logo.png')
const OUT = path.join(__dirname, '..', 'src', 'tui', 'logo-art.ts')

// Text columns. 28 is the brief's starting point; widened to 30 (and the
// `lanczos3` kernel below) after eyeballing the rendered art in a real
// terminal — at 28/nearest the brow read as a solid blob and the five beard
// bars fused into three. Still comfortably under the 34-column cap that
// leaves room for "ALBUS" beside it at 80 columns.
const TEXT_COLUMNS = 30

const WHITE = '#F2F2F2'
const ORANGE = '#F5A623'
const ALPHA_THRESHOLD = 128

interface Cell {
  char: string
  fg?: string
  bg?: string
}

function classify(r: number, b: number): string {
  // The source art has exactly two inks (line-white and the one orange
  // diamond); nearest-by-hue is exact here, not a fuzzy approximation.
  return r > 200 && b < 120 ? ORANGE : WHITE
}

async function main(): Promise<void> {
  // `lanczos3` over `nearest`: nearest-neighbour kept hard aliasing on the
  // triangle's diagonal edges that collapsed the brow into a blob at this
  // column count. lanczos3 blurs those edges, which the alpha threshold
  // below then re-sharpens into a cleaner silhouette.
  const pixelWidth = TEXT_COLUMNS

  // `.metadata()` does NOT reflect a pending `.trim()` in the pipeline — it
  // describes the source file, not the pipeline's output — so the trimmed
  // size has to come from actually running the pipeline once, as raw
  // pixels, before the aspect ratio can be computed. Trimming twice (once
  // here, once implicitly via the untrimmed source) would silently use the
  // wrong (untrimmed, square) aspect ratio and squash the face.
  const { data: trimmedData, info: trimmedInfo } = await sharp(SOURCE)
    .trim()
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const sourceWidth = trimmedInfo.width
  const sourceHeight = trimmedInfo.height

  // Two pixel rows per text row (half-block trick): force an even pixel height.
  const rawPixelHeight = Math.round((pixelWidth * sourceHeight) / sourceWidth)
  const pixelHeight = rawPixelHeight % 2 === 0 ? rawPixelHeight : rawPixelHeight + 1

  const { data, info } = await sharp(trimmedData, {
    raw: { width: sourceWidth, height: sourceHeight, channels: trimmedInfo.channels }
  })
    .resize(pixelWidth, pixelHeight, { kernel: 'lanczos3', fit: 'fill' })
    .raw()
    .toBuffer({ resolveWithObject: true })

  const { width, height, channels } = info
  const pixelAt = (x: number, y: number): { r: number; g: number; b: number; a: number } => {
    if (x < 0 || x >= width || y < 0 || y >= height) return { r: 0, g: 0, b: 0, a: 0 }
    const offset = (y * width + x) * channels
    return { r: data[offset] ?? 0, g: data[offset + 1] ?? 0, b: data[offset + 2] ?? 0, a: data[offset + 3] ?? 0 }
  }

  const rows: Cell[][] = []
  for (let textRow = 0; textRow * 2 < height; textRow++) {
    const row: Cell[] = []
    for (let x = 0; x < width; x++) {
      const topPixel = pixelAt(x, textRow * 2)
      const bottomPixel = pixelAt(x, textRow * 2 + 1)
      const topOpaque = topPixel.a >= ALPHA_THRESHOLD
      const bottomOpaque = bottomPixel.a >= ALPHA_THRESHOLD

      if (topOpaque) {
        const fg = classify(topPixel.r, topPixel.b)
        const bg = bottomOpaque ? classify(bottomPixel.r, bottomPixel.b) : undefined
        row.push(bg === undefined ? { char: '▀', fg } : { char: '▀', fg, bg })
      } else if (bottomOpaque) {
        const fg = classify(bottomPixel.r, bottomPixel.b)
        row.push({ char: '▄', fg })
      } else {
        row.push({ char: ' ' })
      }
    }
    rows.push(row)
  }

  const header = `// Generated by npm run logo:render from docs/logo.png — do not edit by hand\n`
  const body = `export interface LogoCell {\n  char: string\n  fg?: string\n  bg?: string\n}\n\nexport const LOGO: LogoCell[][] = ${JSON.stringify(rows)}\n`
  writeFileSync(OUT, header + body)
  // eslint-disable-next-line no-console
  console.log(`Wrote ${OUT} (${rows.length} rows x ${pixelWidth} cols)`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
